[project]
name = "mcp-example"
version = "0"
requires-python = ">=3.12"
dependencies = [
    "fastmcp~=2.13.0",
    "mcp-hmr",
]

[tool.uv]
package = false

[tool.uv.sources]
mcp-hmr = { workspace = true }
