[project]
name = "fastapi-example"
version = "0"
requires-python = ">=3.12"
dependencies = [
    "fastapi~=0.115.6",
    "uvicorn-hmr",
]

[tool.uv.sources]
uvicorn-hmr = { path = "../../packages/uvicorn-hmr" }
