[project]
name = "fastapi-example"
version = "0"
requires-python = ">=3.12"
dependencies = [
    "fastapi~=0.116.0",
    "uvicorn-hmr",
]

[tool.uv.sources]
uvicorn-hmr = { path = "../../packages/uvicorn-hmr", editable = true }
