[project]
name = "fastapi-example"
version = "0"
requires-python = ">=3.12"
dependencies = [
    "fastapi~=0.120.0",
    "uvicorn-hmr[all]",
]

[tool.uv]
package = false

[tool.uv.sources]
uvicorn-hmr = { workspace = true }
