[project]
name = "fastapi-reloader"
version = "1.3.4"
readme = "README.md"
dependencies = [
    "asgi-lifespan~=2.0",
    "fastapi~=0.115",
    "hmr-reloader>=0.1.0,<1",
]

[tool.uv.sources]
hmr-reloader = { workspace = true }

[project.urls]
Homepage = "https://github.com/promplate/hmr"
Documentation = "https://hmr.promplate.dev"
Repository = "https://github.com/promplate/hmr/tree/HEAD/packages/fastapi-reloader"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
