[project]
name = "fastapi-reloader"
version = "1.3.4"
readme = "README.md"
dependencies = [
    "asgi-lifespan~=2.0",
    "fastapi~=0.115",
]

[project.urls]
Homepage = "https://github.com/promplate/hmr"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
