[project]
name = "hmr-daemon"
version = "0.4.2.1"
dependencies = [
    "hmr>=0.5.0,<0.8",
]

[project.urls]
Homepage = "https://github.com/promplate/hmr"
Documentation = "https://hmr.promplate.dev"
Repository = "https://github.com/promplate/hmr/tree/HEAD/packages/hmr-daemon"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = ["hmr_daemon*"]
